import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { FloatingNav } from "@/utils/floating_nav";
import { IconHome, IconMessage, IconPackage, IconUser } from "@tabler/icons-react";
import Footer from "./components/footer";

const monster = Montserrat({
  subsets: ["latin"],
  weight: "500",
});

export const metadata: Metadata = {
  title: "Blue Ocean Product",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={monster.className}>
        <FloatingNav
          navItems={[
            {
              name: "Home",
              link: "/",
              icon: (
                <IconHome className="h-4 w-4 text-neutral-500 dark:text-white" />
              ),
            },
            {
              name: "Return Policy",
              link: "/return-policy",
              icon: (
                <IconUser className="h-4 w-4 text-neutral-500 dark:text-white" />
              ),
            },
            {
              name: "Product",
              link: "/product",
              icon: (
                <IconPackage className="h-4 w-4 text-neutral-500 dark:text-white" />
              ),
            },
            {
              name: "Contact Us",
              link: "/contact-us",
              icon: (
                <IconMessage className="h-4 w-4 text-neutral-500 dark:text-white" />
              ),
            },
          ]}
        />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
